apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: question-answering
  labels:
    release: nlp-pipeline ## release: prometheus
spec:
  selector:
    matchLabels:
      app: question-answering
  endpoints:   
  - port: web
---
# maybe not needed?
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
spec:
  serviceAccountName: prometheus
  serviceMonitorSelector:
    matchLabels:
      release: nlp-pipeline
  resources:
    requests:
      memory: 300Mi
  enableAdminAPI: false
