apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: question-answering-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: question-answering
  minReplicas: 1   # min
  maxReplicas: 10   # max
  targetCPUUtilizationPercentage: 60   # Set the target CPU utilization percentage
