apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: myapp-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: myapp-deployment
  minReplicas: 2   # Set the minimum number of replicas
  maxReplicas: 6   # Set the maximum number of replicas
  targetCPUUtilizationPercentage: 50   # Set the target CPU utilization percentage
